name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=akaahmad662@gmail.com" > secrets.txt
         -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
